name: Transform Design Tokens

on:
  workflow_dispatch:
  pull_request:

jobs:
  generate_tokens:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Node Dependencies
      run: npm install
    - name: Build Style Dictionary
      run: npm run make
    - name: Commit Generated Platform Deliverables
      id: "auto-commit-action"
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update design tokens